# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev',
                'doc_host': 'https://npinak.github.io',
                'git_url': 'https://github.com/npinak/nbdev',
                'lib_path': 'nbdev'},
  'syms': { 'nbdev.core': { 'nbdev.core.foo': ( 'https://npinak.github.io/core.html#foo',
                                                'https://github.com/npinak/nbdev/blob/master/nbdev/core.py#L7')}}}